name: Benchmarks

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    macOS-benchmark:
        runs-on: macos-26
        steps:
            -   name: 🩵 Checkout repository 🩵
                uses: actions/checkout@v6

            -   name: 🩵 macOS dependencies 🩵
                if: ${{ runner.os == 'macOS' }}
                run: |
                    echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH
                    brew install jemalloc

            -   name: 🩵 Ubuntu dependencies 🩵
                if: ${{ runner.os == 'Linux' }}
                run: |
                    sudo apt install -y libjemalloc-dev

            -   name: 🩵 Benchmark 🩵
                run: |
                    cd ExternalBenchmarks
                    swift package benchmark
